apiVersion: v1
kind: Service
metadata:
  labels:
    app: back
  name: back
spec:
    type: NodePort
    ports:
    - port: 8083
      targetPort: 8083 
    selector:
      app: back
    
