apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "back.fullname" . }}
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "back.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "back.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.secretFile }}
      containers:
      - image: "{{ .Values.registry }}:{{ .Values.tag }}"
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.host_port }}
            protocol: TCP
            name: http
        envFrom:
        - configMapRef:
            name: {{ include "back.fullname" . }}-config
        name: {{ include "back.fullname" . }}
